name: CI
on:
  push:
    branches:
      - master
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Check imports
          run: isort .
      - name: Run black
          run:
            black --check .
      - name: Run flake8
          run: flake8
      - name: Run Mypy
          run: mypy
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start container and run tests
        run: make test
      - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            directory: ./coverage/reports/
            fail_ci_if_error: true
            flags: unittests
            name: codecov-umbrella
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: true
      - name: Stop containers
        run: make stop