version: "3.3"

services:
  webapp:
    build:
      context: ./src
      target: web
    volumes:
      - ./src/app/:/usr/src/app/
    ports:
      - 80:80
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      - db
      - redis
  dev:
    build:
      context: ./src
      target: dev
    volumes:
      - ./src/:/usr/src/
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.1
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: "redis:alpine"

volumes:
  postgres_data: