version: "3.3"

services:
  webapp:
    build:
      context: .
      target: web
    volumes:
      - ./src/app/:/usr/src/app/
    expose:
      - 80
    ports:
      - 8000:80
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      - db
      - redis
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./src/:/usr/src/
      - ./tests/:/usr/tests/
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      - db
  db:
    image: postgres:14.1
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
      - POSTGRES_HOST_AUTH_METHOD=trust
  unittest:
    build:
      context: .
      target: dev
    volumes:
      - ./tests/:/usr/tests/
      - ./src/:/usr/src/
      - ./coverage/reports/:/usr/output/
    command: -c "pytest --cov=./ --cov-report=xml:output/coverage.xml tests/"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://unittest:unittest@dbtest/unittest
    depends_on:
      - dbtest
  dbtest:
    image: postgres:14.1
    expose:
      - 5433
    ports:
      - 5433:5433
    restart: unless-stopped
    environment:
      - POSTGRES_USER=unittest
      - POSTGRES_PASSWORD=unittest
      - POSTGRES_DB=unittest
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - 6379:6379

volumes:
  postgres_data: